POST http://127.0.0.1:8000/auth/register/
Content-Type: application/json

{
    "username": "user3",
    "email": "ggnx7@daouse.com",
    "password":"ayush@1234",
    "confirm_password":"ayush@1234"
}

###

POST http://127.0.0.1:8000/auth/verify-otp/
Content-Type: application/json

{
    "email": "ggnx7@daouse.com",
    "otp": "165940"

}

###

POST http://127.0.0.1:8000/auth/resend-otp/
Content-Type: application/json

{
    "email": "nvl0t@vvatxiy.com"

}


###



POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

{
    "username":"user3",
    "password":"ayush@1234"
}

###

POST http://127.0.0.1:8000/healthcare/form/submit/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMDEwMTMyLCJpYXQiOjE3NDI5MjM3MzIsImp0aSI6Ijg5NmJkMDU2ZDcyMjQyYTQ4MzEwMjRhYjFlMTVkODUzIiwidXNlcl9pZCI6NX0.lSxzztQ8Bt23bd7cPDZ1DZZMm_SP63qW5lw0D-05GuY

 {
    "name": "User3",
    "age": 32,
    "gender": "Prefer not to say",
    "contact_details": "9873442240",
    "chronic_conditions": "Arthritis, High Cholesterol",
    "past_surgeries": "Hip Replacement",
    "allergies": "Penicillin",
    "medications": "Atorvastatin, Ibuprofen",
    "symptoms": "Joint pain and stiffness",
    "symptom_severity": "Moderate",
    "symptom_duration": "Chronic",
    "mental_health_stress": false,
    "mental_health_anxiety": false,
    "mental_health_depression": false,
    "vaccination_history": "Covid-19, Pneumonia",
    "accessibility_needs": "Hearing aid support",
    "pregnancy_status": "Not Applicable",
    "emergency_contact": {
      "name": "Emma Green",
      "relationship": "Daughter",
      "number": "4376543242"
    },
    "health_insurance_provider": "WellCare",
    "health_insurance_policy": "MN123424",
    "preferred_language": "Hindi",
    "research_participation": true
  }
###

GET http://127.0.0.1:8000/healthcare/form/me/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMDA3OTU1LCJpYXQiOjE3NDI5MjE1NTUsImp0aSI6IjFhOGNmY2M4ODgxMjQyYTc4MTFjNWRlMjdmMjg5ZDVjIiwidXNlcl9pZCI6M30.f0Z9loUE4Dxd6o1AsR0Fc4rmINPWWPlFSaFp8uNlmQ4


###

PATCH http://127.0.0.1:8000/healthcare/form/me/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMDA3OTU1LCJpYXQiOjE3NDI5MjE1NTUsImp0aSI6IjFhOGNmY2M4ODgxMjQyYTc4MTFjNWRlMjdmMjg5ZDVjIiwidXNlcl9pZCI6M30.f0Z9loUE4Dxd6o1AsR0Fc4rmINPWWPlFSaFp8uNlmQ4

{
    "name":"User1"
}

###



